# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: subscribing.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11subscribing.proto\x12\tstreaming\"\xf9\x01\n\x0bOfferFilter\x12\x12\n\ncategories\x18\x01 \x03(\t\x12\x19\n\x0cminimalPrice\x18\x02 \x01(\x01H\x00\x88\x01\x01\x12\x19\n\x0cmaximalPrice\x18\x03 \x01(\x01H\x01\x88\x01\x01\x12#\n\x16minimalAvailableAmount\x18\x04 \x01(\rH\x02\x88\x01\x01\x12#\n\x16maximalAvailableAmount\x18\x05 \x01(\rH\x03\x88\x01\x01\x42\x0f\n\r_minimalPriceB\x0f\n\r_maximalPriceB\x19\n\x17_minimalAvailableAmountB\x19\n\x17_maximalAvailableAmount\"\xb6\x01\n\x05Offer\x12\x10\n\x08offer_id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12%\n\x08\x63\x61tegory\x18\x03 \x01(\x0e\x32\x13.streaming.Category\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x1a\n\x12price_integer_part\x18\x05 \x01(\r\x12\x1a\n\x12price_decimal_part\x18\x06 \x01(\r\x12\x18\n\x10\x61vailable_amount\x18\x07 \x01(\r\"p\n\x19\x43reateSubscriptionRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\r\x12\x31\n\x0coffer_filter\x18\x02 \x01(\x0b\x32\x16.streaming.OfferFilterH\x00\x88\x01\x01\x42\x0f\n\r_offer_filter\"F\n\x1a\x43reateSubscriptionResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\r\x12\x17\n\x0fsubscription_id\x18\x02 \x01(\r\"<\n\x10SubscribeRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\r\x12\x17\n\x0fsubscription_id\x18\x02 \x01(\r\"b\n\x11SubscribeResponse\x12\x17\n\x0fsubscription_id\x18\x01 \x01(\r\x12\x13\n\x0bresponse_id\x18\x02 \x01(\r\x12\x1f\n\x05offer\x18\x03 \x01(\x0b\x32\x10.streaming.Offer*V\n\x08\x43\x61tegory\x12\t\n\x05\x46OODS\x10\x00\x12\x0b\n\x07\x43LOTHES\x10\x01\x12\x0f\n\x0b\x45LECTRONICS\x10\x02\x12\x0e\n\nAPPLIANCES\x10\x03\x12\x11\n\rMISCELLANEOUS\x10\x04\x32\xc2\x01\n\x0fOfferObservable\x12\x63\n\x12\x43reateSubscription\x12$.streaming.CreateSubscriptionRequest\x1a%.streaming.CreateSubscriptionResponse\"\x00\x12J\n\tSubscribe\x12\x1b.streaming.SubscribeRequest\x1a\x1c.streaming.SubscribeResponse\"\x00\x30\x01\x42!\n\x0bsr.grpc.genB\x10SubscribingProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'subscribing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013sr.grpc.genB\020SubscribingProtoP\001'
  _globals['_CATEGORY']._serialized_start=817
  _globals['_CATEGORY']._serialized_end=903
  _globals['_OFFERFILTER']._serialized_start=33
  _globals['_OFFERFILTER']._serialized_end=282
  _globals['_OFFER']._serialized_start=285
  _globals['_OFFER']._serialized_end=467
  _globals['_CREATESUBSCRIPTIONREQUEST']._serialized_start=469
  _globals['_CREATESUBSCRIPTIONREQUEST']._serialized_end=581
  _globals['_CREATESUBSCRIPTIONRESPONSE']._serialized_start=583
  _globals['_CREATESUBSCRIPTIONRESPONSE']._serialized_end=653
  _globals['_SUBSCRIBEREQUEST']._serialized_start=655
  _globals['_SUBSCRIBEREQUEST']._serialized_end=715
  _globals['_SUBSCRIBERESPONSE']._serialized_start=717
  _globals['_SUBSCRIBERESPONSE']._serialized_end=815
  _globals['_OFFEROBSERVABLE']._serialized_start=906
  _globals['_OFFEROBSERVABLE']._serialized_end=1100
# @@protoc_insertion_point(module_scope)
